site_name: MasonNLP Wiki 
repo_url: https://github.com/masonnlp/wiki
nav:
    - Home: index.md
    - About: about.md
    - Projects: projects.md
    - Tools: tools.md
    - FAQ: faq.md
theme: readthedocs

